version: '3'
services:
  mininet:
    build:
      context: .
    image: ndexter/vr-tp2
    tty: true
    network_mode: "bridge"
    privileged: true
    environment:
      DISPLAY: "$DISPLAY"
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules




     
