version: '3'
services:
  mininet:
    image: ndexter/vr-tp2
    container_name: mininet
    tty: true
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY="/root/.Xauthority"
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules
     - /home/$USER:/home/nano
